/**
 *
 * $Id$
 */
package mdsd.component_based.validation;

import mdsd.component_based.EAssemblyContext;
import mdsd.component_based.EContainer;
import mdsd.component_based.ESystem;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link mdsd.component_based.EAllocationContext}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface EAllocationContextValidator {
	boolean validate();

	boolean validateControls(EList<EContainer> value);

	boolean validateSpecifiesFor(EList<ESystem> value);

	boolean validateSpecifies(EAssemblyContext value);

	boolean validateSpecifies(EList<ESystem> value);
}
