/**
 *
 * $Id$
 */
package mdsd.component_based.validation;

import mdsd.component_based.EAssemblyContext;
import mdsd.component_based.EComponent;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link mdsd.component_based.EAssemblyViewType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface EAssemblyViewTypeValidator {
	boolean validate();

	boolean validateMainArtifacts(EList<EAssemblyContext> value);

	boolean validateShowsComponents(EList<EComponent> value);
}
