/**
 *
 * $Id$
 */
package mdsd.component_based.validation;

import mdsd.component_based.EComponent;
import mdsd.component_based.ECompositeComponent;
import mdsd.component_based.EContainer;
import mdsd.component_based.ERole;
import mdsd.component_based.ESystem;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link mdsd.component_based.EAssemblyContext}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface EAssemblyContextValidator {
	boolean validate();

	boolean validateName(String value);

	boolean validateRoles(EList<ERole> value);

	boolean validateAllocated(EContainer value);

	boolean validateEncapsulatedByComponent(EList<ECompositeComponent> value);

	boolean validateEncapsulatedBySystem(EList<ESystem> value);

	boolean validateInstantiates(EList<EComponent> value);
}
