/**
 *
 * $Id$
 */
package mdsd.component_based.validation;

import mdsd.component_based.EBranch;
import mdsd.component_based.EExternalCall;
import mdsd.component_based.EInternalAction;
import mdsd.component_based.ELoop;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link mdsd.component_based.EBehaviourDescription}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface EBehaviourDescriptionValidator {
	boolean validate();

	boolean validateInternalAction(EList<EInternalAction> value);

	boolean validateLoop(EList<ELoop> value);

	boolean validateBranch(EList<EBranch> value);

	boolean validateExternalCall(EList<EExternalCall> value);
}
