/**
 *
 * $Id$
 */
package mdsd.component_based.validation;

import mdsd.component_based.EBehaviourDescription;
import mdsd.component_based.EComponent;
import mdsd.component_based.EInterface;
import mdsd.component_based.EService;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link mdsd.component_based.EComponent}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface EComponentValidator {
	boolean validate();

	boolean validateName(String value);

	boolean validateProvidesInterfaceTo(EList<EComponent> value);

	boolean validateBehaviourDescription(EBehaviourDescription value);

	boolean validateUsesInterfaceFrom(EList<EComponent> value);

	boolean validateProvidesDirectly(EList<EService> value);

	boolean validateProvides(EList<EInterface> value);

	boolean validateRequires(EList<EInterface> value);
}
