/**
 *
 * $Id$
 */
package mdsd.component_based.validation;

import mdsd.component_based.EAllocationViewType;
import mdsd.component_based.EEnvironmentViewType;

/**
 * A sample validator interface for {@link mdsd.component_based.EDeploymentViewPoint}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface EDeploymentViewPointValidator {
	boolean validate();

	boolean validateEnvironmentviewtype(EEnvironmentViewType value);

	boolean validateAllocationviewtype(EAllocationViewType value);
}
