/**
 *
 * $Id$
 */
package mdsd.component_based.validation;

import mdsd.component_based.EComponent;
import mdsd.component_based.ERole;
import mdsd.component_based.ESignature;
import mdsd.component_based.ESystem;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link mdsd.component_based.EInterface}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface EInterfaceValidator {
	boolean validate();

	boolean validateName(String value);

	boolean validateSignature(EList<ESignature> value);

	boolean validateResultsIn(EList<ERole> value);

	boolean validateProvidedByComponent(EList<EComponent> value);

	boolean validateProvidedBySystem(EList<ESystem> value);

	boolean validateRequiredByComponent(EList<EComponent> value);

	boolean validateRequiredBySystem(EList<ESystem> value);
}
