/**
 *
 * $Id$
 */
package mdsd.component_based.validation;

import mdsd.component_based.EAssemblyContext;
import mdsd.component_based.EInterface;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link mdsd.component_based.ESystem}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ESystemValidator {
	boolean validate();

	boolean validateProvides(EList<EInterface> value);

	boolean validateRequires(EList<EInterface> value);

	boolean validateEncapsulates(EList<EAssemblyContext> value);
}
