/*
 * generated by Xtext 2.34.0
 */
package org.xtext.example.mydsl.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.xtext.example.mydsl.ide.contentassist.antlr.internal.InternalMyDslParser;
import org.xtext.example.mydsl.services.MyDslGrammarAccess;

public class MyDslParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(MyDslGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, MyDslGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getEViewPointAccess().getAlternatives(), "rule__EViewPoint__Alternatives");
			builder.put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
			builder.put(grammarAccess.getERoleAccess().getAlternatives(), "rule__ERole__Alternatives");
			builder.put(grammarAccess.getEDelegationConnectorAccess().getAlternatives(), "rule__EDelegationConnector__Alternatives");
			builder.put(grammarAccess.getEViewTypeAccess().getAlternatives(), "rule__EViewType__Alternatives");
			builder.put(grammarAccess.getEComponentAccess().getAlternatives(), "rule__EComponent__Alternatives");
			builder.put(grammarAccess.getPossibleReturnTypesAccess().getAlternatives(), "rule__PossibleReturnTypes__Alternatives");
			builder.put(grammarAccess.getPossibleParameterTypesAccess().getAlternatives(), "rule__PossibleParameterTypes__Alternatives");
			builder.put(grammarAccess.getERootAccess().getGroup(), "rule__ERoot__Group__0");
			builder.put(grammarAccess.getERootAccess().getGroup_3(), "rule__ERoot__Group_3__0");
			builder.put(grammarAccess.getERootAccess().getGroup_3_2(), "rule__ERoot__Group_3_2__0");
			builder.put(grammarAccess.getERootAccess().getGroup_4(), "rule__ERoot__Group_4__0");
			builder.put(grammarAccess.getERootAccess().getGroup_4_2(), "rule__ERoot__Group_4_2__0");
			builder.put(grammarAccess.getERootAccess().getGroup_5(), "rule__ERoot__Group_5__0");
			builder.put(grammarAccess.getERootAccess().getGroup_5_2(), "rule__ERoot__Group_5_2__0");
			builder.put(grammarAccess.getERootAccess().getGroup_6(), "rule__ERoot__Group_6__0");
			builder.put(grammarAccess.getERootAccess().getGroup_6_2(), "rule__ERoot__Group_6_2__0");
			builder.put(grammarAccess.getERootAccess().getGroup_7(), "rule__ERoot__Group_7__0");
			builder.put(grammarAccess.getERootAccess().getGroup_7_2(), "rule__ERoot__Group_7_2__0");
			builder.put(grammarAccess.getERootAccess().getGroup_8(), "rule__ERoot__Group_8__0");
			builder.put(grammarAccess.getERootAccess().getGroup_8_2(), "rule__ERoot__Group_8_2__0");
			builder.put(grammarAccess.getERootAccess().getGroup_9(), "rule__ERoot__Group_9__0");
			builder.put(grammarAccess.getERootAccess().getGroup_9_2(), "rule__ERoot__Group_9_2__0");
			builder.put(grammarAccess.getERootAccess().getGroup_10(), "rule__ERoot__Group_10__0");
			builder.put(grammarAccess.getERootAccess().getGroup_10_2(), "rule__ERoot__Group_10_2__0");
			builder.put(grammarAccess.getERootAccess().getGroup_11(), "rule__ERoot__Group_11__0");
			builder.put(grammarAccess.getERootAccess().getGroup_11_2(), "rule__ERoot__Group_11_2__0");
			builder.put(grammarAccess.getERootAccess().getGroup_12(), "rule__ERoot__Group_12__0");
			builder.put(grammarAccess.getERootAccess().getGroup_12_2(), "rule__ERoot__Group_12_2__0");
			builder.put(grammarAccess.getERootAccess().getGroup_13(), "rule__ERoot__Group_13__0");
			builder.put(grammarAccess.getERootAccess().getGroup_13_2(), "rule__ERoot__Group_13_2__0");
			builder.put(grammarAccess.getERootAccess().getGroup_14(), "rule__ERoot__Group_14__0");
			builder.put(grammarAccess.getERootAccess().getGroup_14_2(), "rule__ERoot__Group_14_2__0");
			builder.put(grammarAccess.getERootAccess().getGroup_15(), "rule__ERoot__Group_15__0");
			builder.put(grammarAccess.getERootAccess().getGroup_15_2(), "rule__ERoot__Group_15_2__0");
			builder.put(grammarAccess.getERootAccess().getGroup_16(), "rule__ERoot__Group_16__0");
			builder.put(grammarAccess.getERootAccess().getGroup_16_2(), "rule__ERoot__Group_16_2__0");
			builder.put(grammarAccess.getERootAccess().getGroup_17(), "rule__ERoot__Group_17__0");
			builder.put(grammarAccess.getERootAccess().getGroup_17_2(), "rule__ERoot__Group_17_2__0");
			builder.put(grammarAccess.getERootAccess().getGroup_18(), "rule__ERoot__Group_18__0");
			builder.put(grammarAccess.getERootAccess().getGroup_18_2(), "rule__ERoot__Group_18_2__0");
			builder.put(grammarAccess.getERootAccess().getGroup_19(), "rule__ERoot__Group_19__0");
			builder.put(grammarAccess.getERootAccess().getGroup_19_2(), "rule__ERoot__Group_19_2__0");
			builder.put(grammarAccess.getERootAccess().getGroup_20(), "rule__ERoot__Group_20__0");
			builder.put(grammarAccess.getERootAccess().getGroup_20_2(), "rule__ERoot__Group_20_2__0");
			builder.put(grammarAccess.getERootAccess().getGroup_21(), "rule__ERoot__Group_21__0");
			builder.put(grammarAccess.getERootAccess().getGroup_21_2(), "rule__ERoot__Group_21_2__0");
			builder.put(grammarAccess.getERootAccess().getGroup_22(), "rule__ERoot__Group_22__0");
			builder.put(grammarAccess.getERootAccess().getGroup_22_2(), "rule__ERoot__Group_22_2__0");
			builder.put(grammarAccess.getERootAccess().getGroup_23(), "rule__ERoot__Group_23__0");
			builder.put(grammarAccess.getERootAccess().getGroup_23_2(), "rule__ERoot__Group_23_2__0");
			builder.put(grammarAccess.getERootAccess().getGroup_24(), "rule__ERoot__Group_24__0");
			builder.put(grammarAccess.getERootAccess().getGroup_24_2(), "rule__ERoot__Group_24_2__0");
			builder.put(grammarAccess.getEInterfaceAccess().getGroup(), "rule__EInterface__Group__0");
			builder.put(grammarAccess.getEInterfaceAccess().getGroup_4(), "rule__EInterface__Group_4__0");
			builder.put(grammarAccess.getEInterfaceAccess().getGroup_4_2(), "rule__EInterface__Group_4_2__0");
			builder.put(grammarAccess.getEInterfaceAccess().getGroup_5(), "rule__EInterface__Group_5__0");
			builder.put(grammarAccess.getEInterfaceAccess().getGroup_5_2(), "rule__EInterface__Group_5_2__0");
			builder.put(grammarAccess.getEInterfaceAccess().getGroup_6(), "rule__EInterface__Group_6__0");
			builder.put(grammarAccess.getEInterfaceAccess().getGroup_6_2(), "rule__EInterface__Group_6_2__0");
			builder.put(grammarAccess.getEInterfaceAccess().getGroup_7(), "rule__EInterface__Group_7__0");
			builder.put(grammarAccess.getEInterfaceAccess().getGroup_7_2(), "rule__EInterface__Group_7_2__0");
			builder.put(grammarAccess.getEInterfaceAccess().getGroup_8(), "rule__EInterface__Group_8__0");
			builder.put(grammarAccess.getEInterfaceAccess().getGroup_8_2(), "rule__EInterface__Group_8_2__0");
			builder.put(grammarAccess.getEInterfaceAccess().getGroup_9(), "rule__EInterface__Group_9__0");
			builder.put(grammarAccess.getEInterfaceAccess().getGroup_9_2(), "rule__EInterface__Group_9_2__0");
			builder.put(grammarAccess.getESystemAccess().getGroup(), "rule__ESystem__Group__0");
			builder.put(grammarAccess.getESystemAccess().getGroup_4(), "rule__ESystem__Group_4__0");
			builder.put(grammarAccess.getESystemAccess().getGroup_4_2(), "rule__ESystem__Group_4_2__0");
			builder.put(grammarAccess.getESystemAccess().getGroup_5(), "rule__ESystem__Group_5__0");
			builder.put(grammarAccess.getESystemAccess().getGroup_5_2(), "rule__ESystem__Group_5_2__0");
			builder.put(grammarAccess.getESystemAccess().getGroup_6(), "rule__ESystem__Group_6__0");
			builder.put(grammarAccess.getESystemAccess().getGroup_6_2(), "rule__ESystem__Group_6_2__0");
			builder.put(grammarAccess.getEParameterAccess().getGroup(), "rule__EParameter__Group__0");
			builder.put(grammarAccess.getEParameterAccess().getGroup_4(), "rule__EParameter__Group_4__0");
			builder.put(grammarAccess.getECompositeComponentAccess().getGroup(), "rule__ECompositeComponent__Group__0");
			builder.put(grammarAccess.getECompositeComponentAccess().getGroup_4(), "rule__ECompositeComponent__Group_4__0");
			builder.put(grammarAccess.getECompositeComponentAccess().getGroup_4_2(), "rule__ECompositeComponent__Group_4_2__0");
			builder.put(grammarAccess.getECompositeComponentAccess().getGroup_5(), "rule__ECompositeComponent__Group_5__0");
			builder.put(grammarAccess.getECompositeComponentAccess().getGroup_5_2(), "rule__ECompositeComponent__Group_5_2__0");
			builder.put(grammarAccess.getECompositeComponentAccess().getGroup_6(), "rule__ECompositeComponent__Group_6__0");
			builder.put(grammarAccess.getECompositeComponentAccess().getGroup_6_2(), "rule__ECompositeComponent__Group_6_2__0");
			builder.put(grammarAccess.getECompositeComponentAccess().getGroup_7(), "rule__ECompositeComponent__Group_7__0");
			builder.put(grammarAccess.getECompositeComponentAccess().getGroup_7_2(), "rule__ECompositeComponent__Group_7_2__0");
			builder.put(grammarAccess.getECompositeComponentAccess().getGroup_8(), "rule__ECompositeComponent__Group_8__0");
			builder.put(grammarAccess.getECompositeComponentAccess().getGroup_8_2(), "rule__ECompositeComponent__Group_8_2__0");
			builder.put(grammarAccess.getECompositeComponentAccess().getGroup_9(), "rule__ECompositeComponent__Group_9__0");
			builder.put(grammarAccess.getECompositeComponentAccess().getGroup_9_2(), "rule__ECompositeComponent__Group_9_2__0");
			builder.put(grammarAccess.getECompositeComponentAccess().getGroup_10(), "rule__ECompositeComponent__Group_10__0");
			builder.put(grammarAccess.getEContainerAccess().getGroup(), "rule__EContainer__Group__0");
			builder.put(grammarAccess.getEContainerAccess().getGroup_4(), "rule__EContainer__Group_4__0");
			builder.put(grammarAccess.getEContainerAccess().getGroup_4_2(), "rule__EContainer__Group_4_2__0");
			builder.put(grammarAccess.getEAllocationContextAccess().getGroup(), "rule__EAllocationContext__Group__0");
			builder.put(grammarAccess.getEAllocationContextAccess().getGroup_3(), "rule__EAllocationContext__Group_3__0");
			builder.put(grammarAccess.getEAllocationContextAccess().getGroup_3_2(), "rule__EAllocationContext__Group_3_2__0");
			builder.put(grammarAccess.getEAllocationContextAccess().getGroup_4(), "rule__EAllocationContext__Group_4__0");
			builder.put(grammarAccess.getEAllocationContextAccess().getGroup_4_2(), "rule__EAllocationContext__Group_4_2__0");
			builder.put(grammarAccess.getEAllocationContextAccess().getGroup_5(), "rule__EAllocationContext__Group_5__0");
			builder.put(grammarAccess.getERequiredRoleAccess().getGroup(), "rule__ERequiredRole__Group__0");
			builder.put(grammarAccess.getERequiredRoleAccess().getGroup_4(), "rule__ERequiredRole__Group_4__0");
			builder.put(grammarAccess.getERequiredRoleAccess().getGroup_5(), "rule__ERequiredRole__Group_5__0");
			builder.put(grammarAccess.getEProvidedRoleAccess().getGroup(), "rule__EProvidedRole__Group__0");
			builder.put(grammarAccess.getEProvidedRoleAccess().getGroup_4(), "rule__EProvidedRole__Group_4__0");
			builder.put(grammarAccess.getEProvidedRoleAccess().getGroup_5(), "rule__EProvidedRole__Group_5__0");
			builder.put(grammarAccess.getELinkAccess().getGroup(), "rule__ELink__Group__0");
			builder.put(grammarAccess.getELinkAccess().getGroup_4(), "rule__ELink__Group_4__0");
			builder.put(grammarAccess.getELinkAccess().getGroup_4_2(), "rule__ELink__Group_4_2__0");
			builder.put(grammarAccess.getEAssemblyContextAccess().getGroup(), "rule__EAssemblyContext__Group__0");
			builder.put(grammarAccess.getEAssemblyContextAccess().getGroup_4(), "rule__EAssemblyContext__Group_4__0");
			builder.put(grammarAccess.getEAssemblyContextAccess().getGroup_5(), "rule__EAssemblyContext__Group_5__0");
			builder.put(grammarAccess.getEAssemblyContextAccess().getGroup_5_2(), "rule__EAssemblyContext__Group_5_2__0");
			builder.put(grammarAccess.getEAssemblyContextAccess().getGroup_6(), "rule__EAssemblyContext__Group_6__0");
			builder.put(grammarAccess.getEAssemblyContextAccess().getGroup_6_2(), "rule__EAssemblyContext__Group_6_2__0");
			builder.put(grammarAccess.getEAssemblyContextAccess().getGroup_7(), "rule__EAssemblyContext__Group_7__0");
			builder.put(grammarAccess.getEAssemblyContextAccess().getGroup_7_2(), "rule__EAssemblyContext__Group_7_2__0");
			builder.put(grammarAccess.getEAssemblyContextAccess().getGroup_8(), "rule__EAssemblyContext__Group_8__0");
			builder.put(grammarAccess.getEAssemblyContextAccess().getGroup_8_2(), "rule__EAssemblyContext__Group_8_2__0");
			builder.put(grammarAccess.getEAssemblyConnectorAccess().getGroup(), "rule__EAssemblyConnector__Group__0");
			builder.put(grammarAccess.getEAssemblyConnectorAccess().getGroup_4(), "rule__EAssemblyConnector__Group_4__0");
			builder.put(grammarAccess.getEAssemblyConnectorAccess().getGroup_5(), "rule__EAssemblyConnector__Group_5__0");
			builder.put(grammarAccess.getEProvidedDelegationConnectorAccess().getGroup(), "rule__EProvidedDelegationConnector__Group__0");
			builder.put(grammarAccess.getEProvidedDelegationConnectorAccess().getGroup_3(), "rule__EProvidedDelegationConnector__Group_3__0");
			builder.put(grammarAccess.getEProvidedDelegationConnectorAccess().getGroup_4(), "rule__EProvidedDelegationConnector__Group_4__0");
			builder.put(grammarAccess.getERequiredDelegationConnectorAccess().getGroup(), "rule__ERequiredDelegationConnector__Group__0");
			builder.put(grammarAccess.getERequiredDelegationConnectorAccess().getGroup_3(), "rule__ERequiredDelegationConnector__Group_3__0");
			builder.put(grammarAccess.getERequiredDelegationConnectorAccess().getGroup_4(), "rule__ERequiredDelegationConnector__Group_4__0");
			builder.put(grammarAccess.getESystemIndependentViewPointAccess().getGroup(), "rule__ESystemIndependentViewPoint__Group__0");
			builder.put(grammarAccess.getESystemIndependentViewPointAccess().getGroup_3(), "rule__ESystemIndependentViewPoint__Group_3__0");
			builder.put(grammarAccess.getEAssemblyViewPointAccess().getGroup(), "rule__EAssemblyViewPoint__Group__0");
			builder.put(grammarAccess.getEAssemblyViewPointAccess().getGroup_3(), "rule__EAssemblyViewPoint__Group_3__0");
			builder.put(grammarAccess.getEDeploymentViewPointAccess().getGroup(), "rule__EDeploymentViewPoint__Group__0");
			builder.put(grammarAccess.getERepositoryViewTypeAccess().getGroup(), "rule__ERepositoryViewType__Group__0");
			builder.put(grammarAccess.getERepositoryViewTypeAccess().getGroup_3(), "rule__ERepositoryViewType__Group_3__0");
			builder.put(grammarAccess.getERepositoryViewTypeAccess().getGroup_3_2(), "rule__ERepositoryViewType__Group_3_2__0");
			builder.put(grammarAccess.getERepositoryViewTypeAccess().getGroup_4(), "rule__ERepositoryViewType__Group_4__0");
			builder.put(grammarAccess.getERepositoryViewTypeAccess().getGroup_4_2(), "rule__ERepositoryViewType__Group_4_2__0");
			builder.put(grammarAccess.getEAssemblyViewTypeAccess().getGroup(), "rule__EAssemblyViewType__Group__0");
			builder.put(grammarAccess.getEAssemblyViewTypeAccess().getGroup_3(), "rule__EAssemblyViewType__Group_3__0");
			builder.put(grammarAccess.getEAssemblyViewTypeAccess().getGroup_3_2(), "rule__EAssemblyViewType__Group_3_2__0");
			builder.put(grammarAccess.getEAssemblyViewTypeAccess().getGroup_4(), "rule__EAssemblyViewType__Group_4__0");
			builder.put(grammarAccess.getEAssemblyViewTypeAccess().getGroup_4_2(), "rule__EAssemblyViewType__Group_4_2__0");
			builder.put(grammarAccess.getEAllocationViewTypeAccess().getGroup(), "rule__EAllocationViewType__Group__0");
			builder.put(grammarAccess.getEAllocationViewTypeAccess().getGroup_3(), "rule__EAllocationViewType__Group_3__0");
			builder.put(grammarAccess.getEAllocationViewTypeAccess().getGroup_3_2(), "rule__EAllocationViewType__Group_3_2__0");
			builder.put(grammarAccess.getEEnvironmentViewTypeAccess().getGroup(), "rule__EEnvironmentViewType__Group__0");
			builder.put(grammarAccess.getEEnvironmentViewTypeAccess().getGroup_3(), "rule__EEnvironmentViewType__Group_3__0");
			builder.put(grammarAccess.getEEnvironmentViewTypeAccess().getGroup_3_2(), "rule__EEnvironmentViewType__Group_3_2__0");
			builder.put(grammarAccess.getEEnvironmentViewTypeAccess().getGroup_4(), "rule__EEnvironmentViewType__Group_4__0");
			builder.put(grammarAccess.getEEnvironmentViewTypeAccess().getGroup_4_2(), "rule__EEnvironmentViewType__Group_4_2__0");
			builder.put(grammarAccess.getEComponent_ImplAccess().getGroup(), "rule__EComponent_Impl__Group__0");
			builder.put(grammarAccess.getEComponent_ImplAccess().getGroup_4(), "rule__EComponent_Impl__Group_4__0");
			builder.put(grammarAccess.getEComponent_ImplAccess().getGroup_4_2(), "rule__EComponent_Impl__Group_4_2__0");
			builder.put(grammarAccess.getEComponent_ImplAccess().getGroup_5(), "rule__EComponent_Impl__Group_5__0");
			builder.put(grammarAccess.getEComponent_ImplAccess().getGroup_5_2(), "rule__EComponent_Impl__Group_5_2__0");
			builder.put(grammarAccess.getEComponent_ImplAccess().getGroup_6(), "rule__EComponent_Impl__Group_6__0");
			builder.put(grammarAccess.getEComponent_ImplAccess().getGroup_6_2(), "rule__EComponent_Impl__Group_6_2__0");
			builder.put(grammarAccess.getEComponent_ImplAccess().getGroup_7(), "rule__EComponent_Impl__Group_7__0");
			builder.put(grammarAccess.getEComponent_ImplAccess().getGroup_7_2(), "rule__EComponent_Impl__Group_7_2__0");
			builder.put(grammarAccess.getEComponent_ImplAccess().getGroup_8(), "rule__EComponent_Impl__Group_8__0");
			builder.put(grammarAccess.getEComponent_ImplAccess().getGroup_8_2(), "rule__EComponent_Impl__Group_8_2__0");
			builder.put(grammarAccess.getEComponent_ImplAccess().getGroup_9(), "rule__EComponent_Impl__Group_9__0");
			builder.put(grammarAccess.getEBehaviourDescriptionAccess().getGroup(), "rule__EBehaviourDescription__Group__0");
			builder.put(grammarAccess.getEBehaviourDescriptionAccess().getGroup_3(), "rule__EBehaviourDescription__Group_3__0");
			builder.put(grammarAccess.getEBehaviourDescriptionAccess().getGroup_3_2(), "rule__EBehaviourDescription__Group_3_2__0");
			builder.put(grammarAccess.getEBehaviourDescriptionAccess().getGroup_4(), "rule__EBehaviourDescription__Group_4__0");
			builder.put(grammarAccess.getEBehaviourDescriptionAccess().getGroup_4_2(), "rule__EBehaviourDescription__Group_4_2__0");
			builder.put(grammarAccess.getEBehaviourDescriptionAccess().getGroup_5(), "rule__EBehaviourDescription__Group_5__0");
			builder.put(grammarAccess.getEBehaviourDescriptionAccess().getGroup_5_2(), "rule__EBehaviourDescription__Group_5_2__0");
			builder.put(grammarAccess.getEBehaviourDescriptionAccess().getGroup_6(), "rule__EBehaviourDescription__Group_6__0");
			builder.put(grammarAccess.getEBehaviourDescriptionAccess().getGroup_6_2(), "rule__EBehaviourDescription__Group_6_2__0");
			builder.put(grammarAccess.getEServiceAccess().getGroup(), "rule__EService__Group__0");
			builder.put(grammarAccess.getEInternalActionAccess().getGroup(), "rule__EInternalAction__Group__0");
			builder.put(grammarAccess.getELoopAccess().getGroup(), "rule__ELoop__Group__0");
			builder.put(grammarAccess.getEBranchAccess().getGroup(), "rule__EBranch__Group__0");
			builder.put(grammarAccess.getEExternalCallAccess().getGroup(), "rule__EExternalCall__Group__0");
			builder.put(grammarAccess.getEExternalCallAccess().getGroup_3(), "rule__EExternalCall__Group_3__0");
			builder.put(grammarAccess.getESignatureAccess().getGroup(), "rule__ESignature__Group__0");
			builder.put(grammarAccess.getESignatureAccess().getGroup_4(), "rule__ESignature__Group_4__0");
			builder.put(grammarAccess.getESignatureAccess().getGroup_5(), "rule__ESignature__Group_5__0");
			builder.put(grammarAccess.getESignatureAccess().getGroup_5_2(), "rule__ESignature__Group_5_2__0");
			builder.put(grammarAccess.getESignatureAccess().getGroup_6(), "rule__ESignature__Group_6__0");
			builder.put(grammarAccess.getESignatureAccess().getGroup_6_2(), "rule__ESignature__Group_6_2__0");
			builder.put(grammarAccess.getERepositoryAccess().getGroup(), "rule__ERepository__Group__0");
			builder.put(grammarAccess.getERepositoryAccess().getGroup_3(), "rule__ERepository__Group_3__0");
			builder.put(grammarAccess.getERepositoryAccess().getGroup_3_2(), "rule__ERepository__Group_3_2__0");
			builder.put(grammarAccess.getERepositoryAccess().getGroup_4(), "rule__ERepository__Group_4__0");
			builder.put(grammarAccess.getERepositoryAccess().getGroup_4_2(), "rule__ERepository__Group_4_2__0");
			builder.put(grammarAccess.getERootAccess().getEviewpointAssignment_3_1(), "rule__ERoot__EviewpointAssignment_3_1");
			builder.put(grammarAccess.getERootAccess().getEviewpointAssignment_3_2_1(), "rule__ERoot__EviewpointAssignment_3_2_1");
			builder.put(grammarAccess.getERootAccess().getEviewtypeAssignment_4_1(), "rule__ERoot__EviewtypeAssignment_4_1");
			builder.put(grammarAccess.getERootAccess().getEviewtypeAssignment_4_2_1(), "rule__ERoot__EviewtypeAssignment_4_2_1");
			builder.put(grammarAccess.getERootAccess().getEparameterAssignment_5_1(), "rule__ERoot__EparameterAssignment_5_1");
			builder.put(grammarAccess.getERootAccess().getEparameterAssignment_5_2_1(), "rule__ERoot__EparameterAssignment_5_2_1");
			builder.put(grammarAccess.getERootAccess().getEsignatureAssignment_6_1(), "rule__ERoot__EsignatureAssignment_6_1");
			builder.put(grammarAccess.getERootAccess().getEsignatureAssignment_6_2_1(), "rule__ERoot__EsignatureAssignment_6_2_1");
			builder.put(grammarAccess.getERootAccess().getEdelegationconnectorAssignment_7_1(), "rule__ERoot__EdelegationconnectorAssignment_7_1");
			builder.put(grammarAccess.getERootAccess().getEdelegationconnectorAssignment_7_2_1(), "rule__ERoot__EdelegationconnectorAssignment_7_2_1");
			builder.put(grammarAccess.getERootAccess().getEroleAssignment_8_1(), "rule__ERoot__EroleAssignment_8_1");
			builder.put(grammarAccess.getERootAccess().getEroleAssignment_8_2_1(), "rule__ERoot__EroleAssignment_8_2_1");
			builder.put(grammarAccess.getERootAccess().getElinkAssignment_9_1(), "rule__ERoot__ElinkAssignment_9_1");
			builder.put(grammarAccess.getERootAccess().getElinkAssignment_9_2_1(), "rule__ERoot__ElinkAssignment_9_2_1");
			builder.put(grammarAccess.getERootAccess().getEcontainerAssignment_10_1(), "rule__ERoot__EcontainerAssignment_10_1");
			builder.put(grammarAccess.getERootAccess().getEcontainerAssignment_10_2_1(), "rule__ERoot__EcontainerAssignment_10_2_1");
			builder.put(grammarAccess.getERootAccess().getEassemblyconnectorAssignment_11_1(), "rule__ERoot__EassemblyconnectorAssignment_11_1");
			builder.put(grammarAccess.getERootAccess().getEassemblyconnectorAssignment_11_2_1(), "rule__ERoot__EassemblyconnectorAssignment_11_2_1");
			builder.put(grammarAccess.getERootAccess().getEassemblycontextAssignment_12_1(), "rule__ERoot__EassemblycontextAssignment_12_1");
			builder.put(grammarAccess.getERootAccess().getEassemblycontextAssignment_12_2_1(), "rule__ERoot__EassemblycontextAssignment_12_2_1");
			builder.put(grammarAccess.getERootAccess().getEcomponentAssignment_13_1(), "rule__ERoot__EcomponentAssignment_13_1");
			builder.put(grammarAccess.getERootAccess().getEcomponentAssignment_13_2_1(), "rule__ERoot__EcomponentAssignment_13_2_1");
			builder.put(grammarAccess.getERootAccess().getEserviceAssignment_14_1(), "rule__ERoot__EserviceAssignment_14_1");
			builder.put(grammarAccess.getERootAccess().getEserviceAssignment_14_2_1(), "rule__ERoot__EserviceAssignment_14_2_1");
			builder.put(grammarAccess.getERootAccess().getEinterfaceAssignment_15_1(), "rule__ERoot__EinterfaceAssignment_15_1");
			builder.put(grammarAccess.getERootAccess().getEinterfaceAssignment_15_2_1(), "rule__ERoot__EinterfaceAssignment_15_2_1");
			builder.put(grammarAccess.getERootAccess().getEsystemAssignment_16_1(), "rule__ERoot__EsystemAssignment_16_1");
			builder.put(grammarAccess.getERootAccess().getEsystemAssignment_16_2_1(), "rule__ERoot__EsystemAssignment_16_2_1");
			builder.put(grammarAccess.getERootAccess().getErepositoryAssignment_17_1(), "rule__ERoot__ErepositoryAssignment_17_1");
			builder.put(grammarAccess.getERootAccess().getErepositoryAssignment_17_2_1(), "rule__ERoot__ErepositoryAssignment_17_2_1");
			builder.put(grammarAccess.getERootAccess().getEbehaviourdescriptionAssignment_18_1(), "rule__ERoot__EbehaviourdescriptionAssignment_18_1");
			builder.put(grammarAccess.getERootAccess().getEbehaviourdescriptionAssignment_18_2_1(), "rule__ERoot__EbehaviourdescriptionAssignment_18_2_1");
			builder.put(grammarAccess.getERootAccess().getEexternalcallAssignment_19_1(), "rule__ERoot__EexternalcallAssignment_19_1");
			builder.put(grammarAccess.getERootAccess().getEexternalcallAssignment_19_2_1(), "rule__ERoot__EexternalcallAssignment_19_2_1");
			builder.put(grammarAccess.getERootAccess().getEinternalactionAssignment_20_1(), "rule__ERoot__EinternalactionAssignment_20_1");
			builder.put(grammarAccess.getERootAccess().getEinternalactionAssignment_20_2_1(), "rule__ERoot__EinternalactionAssignment_20_2_1");
			builder.put(grammarAccess.getERootAccess().getEbranchAssignment_21_1(), "rule__ERoot__EbranchAssignment_21_1");
			builder.put(grammarAccess.getERootAccess().getEbranchAssignment_21_2_1(), "rule__ERoot__EbranchAssignment_21_2_1");
			builder.put(grammarAccess.getERootAccess().getEloopAssignment_22_1(), "rule__ERoot__EloopAssignment_22_1");
			builder.put(grammarAccess.getERootAccess().getEloopAssignment_22_2_1(), "rule__ERoot__EloopAssignment_22_2_1");
			builder.put(grammarAccess.getERootAccess().getEcompositecomponentAssignment_23_1(), "rule__ERoot__EcompositecomponentAssignment_23_1");
			builder.put(grammarAccess.getERootAccess().getEcompositecomponentAssignment_23_2_1(), "rule__ERoot__EcompositecomponentAssignment_23_2_1");
			builder.put(grammarAccess.getERootAccess().getEallocationcontextAssignment_24_1(), "rule__ERoot__EallocationcontextAssignment_24_1");
			builder.put(grammarAccess.getERootAccess().getEallocationcontextAssignment_24_2_1(), "rule__ERoot__EallocationcontextAssignment_24_2_1");
			builder.put(grammarAccess.getEInterfaceAccess().getNameAssignment_2(), "rule__EInterface__NameAssignment_2");
			builder.put(grammarAccess.getEInterfaceAccess().getResultsInAssignment_4_1(), "rule__EInterface__ResultsInAssignment_4_1");
			builder.put(grammarAccess.getEInterfaceAccess().getResultsInAssignment_4_2_1(), "rule__EInterface__ResultsInAssignment_4_2_1");
			builder.put(grammarAccess.getEInterfaceAccess().getProvidedByComponentAssignment_5_1(), "rule__EInterface__ProvidedByComponentAssignment_5_1");
			builder.put(grammarAccess.getEInterfaceAccess().getProvidedByComponentAssignment_5_2_1(), "rule__EInterface__ProvidedByComponentAssignment_5_2_1");
			builder.put(grammarAccess.getEInterfaceAccess().getProvidedBySystemAssignment_6_1(), "rule__EInterface__ProvidedBySystemAssignment_6_1");
			builder.put(grammarAccess.getEInterfaceAccess().getProvidedBySystemAssignment_6_2_1(), "rule__EInterface__ProvidedBySystemAssignment_6_2_1");
			builder.put(grammarAccess.getEInterfaceAccess().getRequiredByComponentAssignment_7_1(), "rule__EInterface__RequiredByComponentAssignment_7_1");
			builder.put(grammarAccess.getEInterfaceAccess().getRequiredByComponentAssignment_7_2_1(), "rule__EInterface__RequiredByComponentAssignment_7_2_1");
			builder.put(grammarAccess.getEInterfaceAccess().getRequiredBySystemAssignment_8_1(), "rule__EInterface__RequiredBySystemAssignment_8_1");
			builder.put(grammarAccess.getEInterfaceAccess().getRequiredBySystemAssignment_8_2_1(), "rule__EInterface__RequiredBySystemAssignment_8_2_1");
			builder.put(grammarAccess.getEInterfaceAccess().getSignatureAssignment_9_1(), "rule__EInterface__SignatureAssignment_9_1");
			builder.put(grammarAccess.getEInterfaceAccess().getSignatureAssignment_9_2_1(), "rule__EInterface__SignatureAssignment_9_2_1");
			builder.put(grammarAccess.getESystemAccess().getNameAssignment_2(), "rule__ESystem__NameAssignment_2");
			builder.put(grammarAccess.getESystemAccess().getProvidesAssignment_4_1(), "rule__ESystem__ProvidesAssignment_4_1");
			builder.put(grammarAccess.getESystemAccess().getProvidesAssignment_4_2_1(), "rule__ESystem__ProvidesAssignment_4_2_1");
			builder.put(grammarAccess.getESystemAccess().getRequiresAssignment_5_1(), "rule__ESystem__RequiresAssignment_5_1");
			builder.put(grammarAccess.getESystemAccess().getRequiresAssignment_5_2_1(), "rule__ESystem__RequiresAssignment_5_2_1");
			builder.put(grammarAccess.getESystemAccess().getEncapsulatesAssignment_6_1(), "rule__ESystem__EncapsulatesAssignment_6_1");
			builder.put(grammarAccess.getESystemAccess().getEncapsulatesAssignment_6_2_1(), "rule__ESystem__EncapsulatesAssignment_6_2_1");
			builder.put(grammarAccess.getEParameterAccess().getNameAssignment_2(), "rule__EParameter__NameAssignment_2");
			builder.put(grammarAccess.getEParameterAccess().getTypeAssignment_4_1(), "rule__EParameter__TypeAssignment_4_1");
			builder.put(grammarAccess.getECompositeComponentAccess().getNameAssignment_2(), "rule__ECompositeComponent__NameAssignment_2");
			builder.put(grammarAccess.getECompositeComponentAccess().getProvidesInterfaceToAssignment_4_1(), "rule__ECompositeComponent__ProvidesInterfaceToAssignment_4_1");
			builder.put(grammarAccess.getECompositeComponentAccess().getProvidesInterfaceToAssignment_4_2_1(), "rule__ECompositeComponent__ProvidesInterfaceToAssignment_4_2_1");
			builder.put(grammarAccess.getECompositeComponentAccess().getUsesInterfaceFromAssignment_5_1(), "rule__ECompositeComponent__UsesInterfaceFromAssignment_5_1");
			builder.put(grammarAccess.getECompositeComponentAccess().getUsesInterfaceFromAssignment_5_2_1(), "rule__ECompositeComponent__UsesInterfaceFromAssignment_5_2_1");
			builder.put(grammarAccess.getECompositeComponentAccess().getProvidesDirectlyAssignment_6_1(), "rule__ECompositeComponent__ProvidesDirectlyAssignment_6_1");
			builder.put(grammarAccess.getECompositeComponentAccess().getProvidesDirectlyAssignment_6_2_1(), "rule__ECompositeComponent__ProvidesDirectlyAssignment_6_2_1");
			builder.put(grammarAccess.getECompositeComponentAccess().getProvidesAssignment_7_1(), "rule__ECompositeComponent__ProvidesAssignment_7_1");
			builder.put(grammarAccess.getECompositeComponentAccess().getProvidesAssignment_7_2_1(), "rule__ECompositeComponent__ProvidesAssignment_7_2_1");
			builder.put(grammarAccess.getECompositeComponentAccess().getRequiresAssignment_8_1(), "rule__ECompositeComponent__RequiresAssignment_8_1");
			builder.put(grammarAccess.getECompositeComponentAccess().getRequiresAssignment_8_2_1(), "rule__ECompositeComponent__RequiresAssignment_8_2_1");
			builder.put(grammarAccess.getECompositeComponentAccess().getEncapsulatesAssignment_9_1(), "rule__ECompositeComponent__EncapsulatesAssignment_9_1");
			builder.put(grammarAccess.getECompositeComponentAccess().getEncapsulatesAssignment_9_2_1(), "rule__ECompositeComponent__EncapsulatesAssignment_9_2_1");
			builder.put(grammarAccess.getECompositeComponentAccess().getBehaviourDescriptionAssignment_10_1(), "rule__ECompositeComponent__BehaviourDescriptionAssignment_10_1");
			builder.put(grammarAccess.getEContainerAccess().getNameAssignment_2(), "rule__EContainer__NameAssignment_2");
			builder.put(grammarAccess.getEContainerAccess().getConnectedToAssignment_4_1(), "rule__EContainer__ConnectedToAssignment_4_1");
			builder.put(grammarAccess.getEContainerAccess().getConnectedToAssignment_4_2_1(), "rule__EContainer__ConnectedToAssignment_4_2_1");
			builder.put(grammarAccess.getEAllocationContextAccess().getControlsAssignment_3_1(), "rule__EAllocationContext__ControlsAssignment_3_1");
			builder.put(grammarAccess.getEAllocationContextAccess().getControlsAssignment_3_2_1(), "rule__EAllocationContext__ControlsAssignment_3_2_1");
			builder.put(grammarAccess.getEAllocationContextAccess().getSpecifiesForAssignment_4_1(), "rule__EAllocationContext__SpecifiesForAssignment_4_1");
			builder.put(grammarAccess.getEAllocationContextAccess().getSpecifiesForAssignment_4_2_1(), "rule__EAllocationContext__SpecifiesForAssignment_4_2_1");
			builder.put(grammarAccess.getEAllocationContextAccess().getSpecifiesAssignment_5_1(), "rule__EAllocationContext__SpecifiesAssignment_5_1");
			builder.put(grammarAccess.getERequiredRoleAccess().getNameAssignment_2(), "rule__ERequiredRole__NameAssignment_2");
			builder.put(grammarAccess.getERequiredRoleAccess().getRoleOfAssignment_4_1(), "rule__ERequiredRole__RoleOfAssignment_4_1");
			builder.put(grammarAccess.getERequiredRoleAccess().getLinkedToAssignment_5_1(), "rule__ERequiredRole__LinkedToAssignment_5_1");
			builder.put(grammarAccess.getEProvidedRoleAccess().getNameAssignment_2(), "rule__EProvidedRole__NameAssignment_2");
			builder.put(grammarAccess.getEProvidedRoleAccess().getRoleOfAssignment_4_1(), "rule__EProvidedRole__RoleOfAssignment_4_1");
			builder.put(grammarAccess.getEProvidedRoleAccess().getLinkedFromAssignment_5_1(), "rule__EProvidedRole__LinkedFromAssignment_5_1");
			builder.put(grammarAccess.getELinkAccess().getNameAssignment_2(), "rule__ELink__NameAssignment_2");
			builder.put(grammarAccess.getELinkAccess().getConnectsAssignment_4_1(), "rule__ELink__ConnectsAssignment_4_1");
			builder.put(grammarAccess.getELinkAccess().getConnectsAssignment_4_2_1(), "rule__ELink__ConnectsAssignment_4_2_1");
			builder.put(grammarAccess.getEAssemblyContextAccess().getNameAssignment_2(), "rule__EAssemblyContext__NameAssignment_2");
			builder.put(grammarAccess.getEAssemblyContextAccess().getAllocatedAssignment_4_1(), "rule__EAssemblyContext__AllocatedAssignment_4_1");
			builder.put(grammarAccess.getEAssemblyContextAccess().getEncapsulatedByComponentAssignment_5_1(), "rule__EAssemblyContext__EncapsulatedByComponentAssignment_5_1");
			builder.put(grammarAccess.getEAssemblyContextAccess().getEncapsulatedByComponentAssignment_5_2_1(), "rule__EAssemblyContext__EncapsulatedByComponentAssignment_5_2_1");
			builder.put(grammarAccess.getEAssemblyContextAccess().getEncapsulatedBySystemAssignment_6_1(), "rule__EAssemblyContext__EncapsulatedBySystemAssignment_6_1");
			builder.put(grammarAccess.getEAssemblyContextAccess().getEncapsulatedBySystemAssignment_6_2_1(), "rule__EAssemblyContext__EncapsulatedBySystemAssignment_6_2_1");
			builder.put(grammarAccess.getEAssemblyContextAccess().getInstantiatesAssignment_7_1(), "rule__EAssemblyContext__InstantiatesAssignment_7_1");
			builder.put(grammarAccess.getEAssemblyContextAccess().getInstantiatesAssignment_7_2_1(), "rule__EAssemblyContext__InstantiatesAssignment_7_2_1");
			builder.put(grammarAccess.getEAssemblyContextAccess().getRolesAssignment_8_1(), "rule__EAssemblyContext__RolesAssignment_8_1");
			builder.put(grammarAccess.getEAssemblyContextAccess().getRolesAssignment_8_2_1(), "rule__EAssemblyContext__RolesAssignment_8_2_1");
			builder.put(grammarAccess.getEAssemblyConnectorAccess().getNameAssignment_2(), "rule__EAssemblyConnector__NameAssignment_2");
			builder.put(grammarAccess.getEAssemblyConnectorAccess().getLinkToAssignment_4_1(), "rule__EAssemblyConnector__LinkToAssignment_4_1");
			builder.put(grammarAccess.getEAssemblyConnectorAccess().getLinkFromAssignment_5_1(), "rule__EAssemblyConnector__LinkFromAssignment_5_1");
			builder.put(grammarAccess.getEProvidedDelegationConnectorAccess().getLinkFromAssignment_3_1(), "rule__EProvidedDelegationConnector__LinkFromAssignment_3_1");
			builder.put(grammarAccess.getEProvidedDelegationConnectorAccess().getLinkToAssignment_4_1(), "rule__EProvidedDelegationConnector__LinkToAssignment_4_1");
			builder.put(grammarAccess.getERequiredDelegationConnectorAccess().getLinkFromAssignment_3_1(), "rule__ERequiredDelegationConnector__LinkFromAssignment_3_1");
			builder.put(grammarAccess.getERequiredDelegationConnectorAccess().getLinkToAssignment_4_1(), "rule__ERequiredDelegationConnector__LinkToAssignment_4_1");
			builder.put(grammarAccess.getESystemIndependentViewPointAccess().getRepositoryViewTypeAssignment_3_1(), "rule__ESystemIndependentViewPoint__RepositoryViewTypeAssignment_3_1");
			builder.put(grammarAccess.getEAssemblyViewPointAccess().getAssemblyViewTypeAssignment_3_1(), "rule__EAssemblyViewPoint__AssemblyViewTypeAssignment_3_1");
			builder.put(grammarAccess.getEDeploymentViewPointAccess().getAllocationViewTypeAssignment_4(), "rule__EDeploymentViewPoint__AllocationViewTypeAssignment_4");
			builder.put(grammarAccess.getEDeploymentViewPointAccess().getEnvironmentViewTypeAssignment_6(), "rule__EDeploymentViewPoint__EnvironmentViewTypeAssignment_6");
			builder.put(grammarAccess.getERepositoryViewTypeAccess().getShowsInterfacesAssignment_3_1(), "rule__ERepositoryViewType__ShowsInterfacesAssignment_3_1");
			builder.put(grammarAccess.getERepositoryViewTypeAccess().getShowsInterfacesAssignment_3_2_1(), "rule__ERepositoryViewType__ShowsInterfacesAssignment_3_2_1");
			builder.put(grammarAccess.getERepositoryViewTypeAccess().getShowsComponentsAssignment_4_1(), "rule__ERepositoryViewType__ShowsComponentsAssignment_4_1");
			builder.put(grammarAccess.getERepositoryViewTypeAccess().getShowsComponentsAssignment_4_2_1(), "rule__ERepositoryViewType__ShowsComponentsAssignment_4_2_1");
			builder.put(grammarAccess.getEAssemblyViewTypeAccess().getMainArtifactsAssignment_3_1(), "rule__EAssemblyViewType__MainArtifactsAssignment_3_1");
			builder.put(grammarAccess.getEAssemblyViewTypeAccess().getMainArtifactsAssignment_3_2_1(), "rule__EAssemblyViewType__MainArtifactsAssignment_3_2_1");
			builder.put(grammarAccess.getEAssemblyViewTypeAccess().getShowsComponentsAssignment_4_1(), "rule__EAssemblyViewType__ShowsComponentsAssignment_4_1");
			builder.put(grammarAccess.getEAssemblyViewTypeAccess().getShowsComponentsAssignment_4_2_1(), "rule__EAssemblyViewType__ShowsComponentsAssignment_4_2_1");
			builder.put(grammarAccess.getEAllocationViewTypeAccess().getIncludesAssignment_3_1(), "rule__EAllocationViewType__IncludesAssignment_3_1");
			builder.put(grammarAccess.getEAllocationViewTypeAccess().getIncludesAssignment_3_2_1(), "rule__EAllocationViewType__IncludesAssignment_3_2_1");
			builder.put(grammarAccess.getEEnvironmentViewTypeAccess().getShowsLinksAssignment_3_1(), "rule__EEnvironmentViewType__ShowsLinksAssignment_3_1");
			builder.put(grammarAccess.getEEnvironmentViewTypeAccess().getShowsLinksAssignment_3_2_1(), "rule__EEnvironmentViewType__ShowsLinksAssignment_3_2_1");
			builder.put(grammarAccess.getEEnvironmentViewTypeAccess().getShowsContainersAssignment_4_1(), "rule__EEnvironmentViewType__ShowsContainersAssignment_4_1");
			builder.put(grammarAccess.getEEnvironmentViewTypeAccess().getShowsContainersAssignment_4_2_1(), "rule__EEnvironmentViewType__ShowsContainersAssignment_4_2_1");
			builder.put(grammarAccess.getEComponent_ImplAccess().getNameAssignment_2(), "rule__EComponent_Impl__NameAssignment_2");
			builder.put(grammarAccess.getEComponent_ImplAccess().getProvidesInterfaceToAssignment_4_1(), "rule__EComponent_Impl__ProvidesInterfaceToAssignment_4_1");
			builder.put(grammarAccess.getEComponent_ImplAccess().getProvidesInterfaceToAssignment_4_2_1(), "rule__EComponent_Impl__ProvidesInterfaceToAssignment_4_2_1");
			builder.put(grammarAccess.getEComponent_ImplAccess().getUsesInterfaceFromAssignment_5_1(), "rule__EComponent_Impl__UsesInterfaceFromAssignment_5_1");
			builder.put(grammarAccess.getEComponent_ImplAccess().getUsesInterfaceFromAssignment_5_2_1(), "rule__EComponent_Impl__UsesInterfaceFromAssignment_5_2_1");
			builder.put(grammarAccess.getEComponent_ImplAccess().getProvidesDirectlyAssignment_6_1(), "rule__EComponent_Impl__ProvidesDirectlyAssignment_6_1");
			builder.put(grammarAccess.getEComponent_ImplAccess().getProvidesDirectlyAssignment_6_2_1(), "rule__EComponent_Impl__ProvidesDirectlyAssignment_6_2_1");
			builder.put(grammarAccess.getEComponent_ImplAccess().getProvidesAssignment_7_1(), "rule__EComponent_Impl__ProvidesAssignment_7_1");
			builder.put(grammarAccess.getEComponent_ImplAccess().getProvidesAssignment_7_2_1(), "rule__EComponent_Impl__ProvidesAssignment_7_2_1");
			builder.put(grammarAccess.getEComponent_ImplAccess().getRequiresAssignment_8_1(), "rule__EComponent_Impl__RequiresAssignment_8_1");
			builder.put(grammarAccess.getEComponent_ImplAccess().getRequiresAssignment_8_2_1(), "rule__EComponent_Impl__RequiresAssignment_8_2_1");
			builder.put(grammarAccess.getEComponent_ImplAccess().getBehaviourDescriptionAssignment_9_1(), "rule__EComponent_Impl__BehaviourDescriptionAssignment_9_1");
			builder.put(grammarAccess.getEBehaviourDescriptionAccess().getInternalActionAssignment_3_1(), "rule__EBehaviourDescription__InternalActionAssignment_3_1");
			builder.put(grammarAccess.getEBehaviourDescriptionAccess().getInternalActionAssignment_3_2_1(), "rule__EBehaviourDescription__InternalActionAssignment_3_2_1");
			builder.put(grammarAccess.getEBehaviourDescriptionAccess().getLoopAssignment_4_1(), "rule__EBehaviourDescription__LoopAssignment_4_1");
			builder.put(grammarAccess.getEBehaviourDescriptionAccess().getLoopAssignment_4_2_1(), "rule__EBehaviourDescription__LoopAssignment_4_2_1");
			builder.put(grammarAccess.getEBehaviourDescriptionAccess().getBranchAssignment_5_1(), "rule__EBehaviourDescription__BranchAssignment_5_1");
			builder.put(grammarAccess.getEBehaviourDescriptionAccess().getBranchAssignment_5_2_1(), "rule__EBehaviourDescription__BranchAssignment_5_2_1");
			builder.put(grammarAccess.getEBehaviourDescriptionAccess().getExternalCallAssignment_6_1(), "rule__EBehaviourDescription__ExternalCallAssignment_6_1");
			builder.put(grammarAccess.getEBehaviourDescriptionAccess().getExternalCallAssignment_6_2_1(), "rule__EBehaviourDescription__ExternalCallAssignment_6_2_1");
			builder.put(grammarAccess.getEServiceAccess().getNameAssignment_2(), "rule__EService__NameAssignment_2");
			builder.put(grammarAccess.getEExternalCallAccess().getToAssignment_3_1(), "rule__EExternalCall__ToAssignment_3_1");
			builder.put(grammarAccess.getESignatureAccess().getNameAssignment_2(), "rule__ESignature__NameAssignment_2");
			builder.put(grammarAccess.getESignatureAccess().getReturnTypeAssignment_4_1(), "rule__ESignature__ReturnTypeAssignment_4_1");
			builder.put(grammarAccess.getESignatureAccess().getCorrespondsToAssignment_5_1(), "rule__ESignature__CorrespondsToAssignment_5_1");
			builder.put(grammarAccess.getESignatureAccess().getCorrespondsToAssignment_5_2_1(), "rule__ESignature__CorrespondsToAssignment_5_2_1");
			builder.put(grammarAccess.getESignatureAccess().getParameterAssignment_6_1(), "rule__ESignature__ParameterAssignment_6_1");
			builder.put(grammarAccess.getESignatureAccess().getParameterAssignment_6_2_1(), "rule__ESignature__ParameterAssignment_6_2_1");
			builder.put(grammarAccess.getERepositoryAccess().getComponentAssignment_3_1(), "rule__ERepository__ComponentAssignment_3_1");
			builder.put(grammarAccess.getERepositoryAccess().getComponentAssignment_3_2_1(), "rule__ERepository__ComponentAssignment_3_2_1");
			builder.put(grammarAccess.getERepositoryAccess().getInterfaceAssignment_4_1(), "rule__ERepository__InterfaceAssignment_4_1");
			builder.put(grammarAccess.getERepositoryAccess().getInterfaceAssignment_4_2_1(), "rule__ERepository__InterfaceAssignment_4_2_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private MyDslGrammarAccess grammarAccess;

	@Override
	protected InternalMyDslParser createParser() {
		InternalMyDslParser result = new InternalMyDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public MyDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MyDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
