/*
 * generated by Xtext 2.34.0
 */
package org.xtext.example.mydsl.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.xtext.example.mydsl.ide.contentassist.antlr.internal.InternalMyDslParser;
import org.xtext.example.mydsl.services.MyDslGrammarAccess;

public class MyDslParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(MyDslGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, MyDslGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getEViewPointAccess().getAlternatives(), "rule__EViewPoint__Alternatives");
			builder.put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
			builder.put(grammarAccess.getERoleAccess().getAlternatives(), "rule__ERole__Alternatives");
			builder.put(grammarAccess.getEDelegationConnectorAccess().getAlternatives(), "rule__EDelegationConnector__Alternatives");
			builder.put(grammarAccess.getEViewTypeAccess().getAlternatives(), "rule__EViewType__Alternatives");
			builder.put(grammarAccess.getEComponentAccess().getAlternatives(), "rule__EComponent__Alternatives");
			builder.put(grammarAccess.getPossibleReturnTypesAccess().getAlternatives(), "rule__PossibleReturnTypes__Alternatives");
			builder.put(grammarAccess.getPossibleParameterTypesAccess().getAlternatives(), "rule__PossibleParameterTypes__Alternatives");
			builder.put(grammarAccess.getEParameterAccess().getGroup(), "rule__EParameter__Group__0");
			builder.put(grammarAccess.getEParameterAccess().getGroup_3(), "rule__EParameter__Group_3__0");
			builder.put(grammarAccess.getESystemAccess().getGroup(), "rule__ESystem__Group__0");
			builder.put(grammarAccess.getESystemAccess().getGroup_2(), "rule__ESystem__Group_2__0");
			builder.put(grammarAccess.getESystemAccess().getGroup_2_2(), "rule__ESystem__Group_2_2__0");
			builder.put(grammarAccess.getESystemAccess().getGroup_3(), "rule__ESystem__Group_3__0");
			builder.put(grammarAccess.getESystemAccess().getGroup_3_2(), "rule__ESystem__Group_3_2__0");
			builder.put(grammarAccess.getESystemAccess().getGroup_4(), "rule__ESystem__Group_4__0");
			builder.put(grammarAccess.getESystemAccess().getGroup_4_2(), "rule__ESystem__Group_4_2__0");
			builder.put(grammarAccess.getECompositeComponentAccess().getGroup(), "rule__ECompositeComponent__Group__0");
			builder.put(grammarAccess.getECompositeComponentAccess().getGroup_3(), "rule__ECompositeComponent__Group_3__0");
			builder.put(grammarAccess.getECompositeComponentAccess().getGroup_3_2(), "rule__ECompositeComponent__Group_3_2__0");
			builder.put(grammarAccess.getECompositeComponentAccess().getGroup_4(), "rule__ECompositeComponent__Group_4__0");
			builder.put(grammarAccess.getECompositeComponentAccess().getGroup_4_2(), "rule__ECompositeComponent__Group_4_2__0");
			builder.put(grammarAccess.getECompositeComponentAccess().getGroup_5(), "rule__ECompositeComponent__Group_5__0");
			builder.put(grammarAccess.getECompositeComponentAccess().getGroup_5_2(), "rule__ECompositeComponent__Group_5_2__0");
			builder.put(grammarAccess.getECompositeComponentAccess().getGroup_6(), "rule__ECompositeComponent__Group_6__0");
			builder.put(grammarAccess.getECompositeComponentAccess().getGroup_6_2(), "rule__ECompositeComponent__Group_6_2__0");
			builder.put(grammarAccess.getECompositeComponentAccess().getGroup_7(), "rule__ECompositeComponent__Group_7__0");
			builder.put(grammarAccess.getECompositeComponentAccess().getGroup_7_2(), "rule__ECompositeComponent__Group_7_2__0");
			builder.put(grammarAccess.getECompositeComponentAccess().getGroup_8(), "rule__ECompositeComponent__Group_8__0");
			builder.put(grammarAccess.getECompositeComponentAccess().getGroup_8_2(), "rule__ECompositeComponent__Group_8_2__0");
			builder.put(grammarAccess.getECompositeComponentAccess().getGroup_9(), "rule__ECompositeComponent__Group_9__0");
			builder.put(grammarAccess.getEContainerAccess().getGroup(), "rule__EContainer__Group__0");
			builder.put(grammarAccess.getEContainerAccess().getGroup_3(), "rule__EContainer__Group_3__0");
			builder.put(grammarAccess.getEContainerAccess().getGroup_3_2(), "rule__EContainer__Group_3_2__0");
			builder.put(grammarAccess.getEAllocationContextAccess().getGroup(), "rule__EAllocationContext__Group__0");
			builder.put(grammarAccess.getEAllocationContextAccess().getGroup_2(), "rule__EAllocationContext__Group_2__0");
			builder.put(grammarAccess.getEAllocationContextAccess().getGroup_2_2(), "rule__EAllocationContext__Group_2_2__0");
			builder.put(grammarAccess.getEAllocationContextAccess().getGroup_3(), "rule__EAllocationContext__Group_3__0");
			builder.put(grammarAccess.getEAllocationContextAccess().getGroup_3_2(), "rule__EAllocationContext__Group_3_2__0");
			builder.put(grammarAccess.getEAllocationContextAccess().getGroup_4(), "rule__EAllocationContext__Group_4__0");
			builder.put(grammarAccess.getERequiredRoleAccess().getGroup(), "rule__ERequiredRole__Group__0");
			builder.put(grammarAccess.getERequiredRoleAccess().getGroup_2(), "rule__ERequiredRole__Group_2__0");
			builder.put(grammarAccess.getERequiredRoleAccess().getGroup_3(), "rule__ERequiredRole__Group_3__0");
			builder.put(grammarAccess.getEProvidedRoleAccess().getGroup(), "rule__EProvidedRole__Group__0");
			builder.put(grammarAccess.getEProvidedRoleAccess().getGroup_2(), "rule__EProvidedRole__Group_2__0");
			builder.put(grammarAccess.getEProvidedRoleAccess().getGroup_3(), "rule__EProvidedRole__Group_3__0");
			builder.put(grammarAccess.getELinkAccess().getGroup(), "rule__ELink__Group__0");
			builder.put(grammarAccess.getELinkAccess().getGroup_3(), "rule__ELink__Group_3__0");
			builder.put(grammarAccess.getELinkAccess().getGroup_3_2(), "rule__ELink__Group_3_2__0");
			builder.put(grammarAccess.getEAssemblyContextAccess().getGroup(), "rule__EAssemblyContext__Group__0");
			builder.put(grammarAccess.getEAssemblyContextAccess().getGroup_3(), "rule__EAssemblyContext__Group_3__0");
			builder.put(grammarAccess.getEAssemblyContextAccess().getGroup_4(), "rule__EAssemblyContext__Group_4__0");
			builder.put(grammarAccess.getEAssemblyContextAccess().getGroup_4_2(), "rule__EAssemblyContext__Group_4_2__0");
			builder.put(grammarAccess.getEAssemblyContextAccess().getGroup_5(), "rule__EAssemblyContext__Group_5__0");
			builder.put(grammarAccess.getEAssemblyContextAccess().getGroup_5_2(), "rule__EAssemblyContext__Group_5_2__0");
			builder.put(grammarAccess.getEAssemblyContextAccess().getGroup_6(), "rule__EAssemblyContext__Group_6__0");
			builder.put(grammarAccess.getEAssemblyContextAccess().getGroup_6_2(), "rule__EAssemblyContext__Group_6_2__0");
			builder.put(grammarAccess.getEAssemblyContextAccess().getGroup_7(), "rule__EAssemblyContext__Group_7__0");
			builder.put(grammarAccess.getEAssemblyContextAccess().getGroup_7_2(), "rule__EAssemblyContext__Group_7_2__0");
			builder.put(grammarAccess.getEAssemblyConnectorAccess().getGroup(), "rule__EAssemblyConnector__Group__0");
			builder.put(grammarAccess.getEAssemblyConnectorAccess().getGroup_2(), "rule__EAssemblyConnector__Group_2__0");
			builder.put(grammarAccess.getEAssemblyConnectorAccess().getGroup_3(), "rule__EAssemblyConnector__Group_3__0");
			builder.put(grammarAccess.getEProvidedDelegationConnectorAccess().getGroup(), "rule__EProvidedDelegationConnector__Group__0");
			builder.put(grammarAccess.getEProvidedDelegationConnectorAccess().getGroup_2(), "rule__EProvidedDelegationConnector__Group_2__0");
			builder.put(grammarAccess.getEProvidedDelegationConnectorAccess().getGroup_3(), "rule__EProvidedDelegationConnector__Group_3__0");
			builder.put(grammarAccess.getERequiredDelegationConnectorAccess().getGroup(), "rule__ERequiredDelegationConnector__Group__0");
			builder.put(grammarAccess.getERequiredDelegationConnectorAccess().getGroup_2(), "rule__ERequiredDelegationConnector__Group_2__0");
			builder.put(grammarAccess.getERequiredDelegationConnectorAccess().getGroup_3(), "rule__ERequiredDelegationConnector__Group_3__0");
			builder.put(grammarAccess.getESystemIndependentViewPointAccess().getGroup(), "rule__ESystemIndependentViewPoint__Group__0");
			builder.put(grammarAccess.getESystemIndependentViewPointAccess().getGroup_2(), "rule__ESystemIndependentViewPoint__Group_2__0");
			builder.put(grammarAccess.getEAssemblyViewPointAccess().getGroup(), "rule__EAssemblyViewPoint__Group__0");
			builder.put(grammarAccess.getEAssemblyViewPointAccess().getGroup_2(), "rule__EAssemblyViewPoint__Group_2__0");
			builder.put(grammarAccess.getEDeploymentViewPointAccess().getGroup(), "rule__EDeploymentViewPoint__Group__0");
			builder.put(grammarAccess.getERepositoryViewTypeAccess().getGroup(), "rule__ERepositoryViewType__Group__0");
			builder.put(grammarAccess.getERepositoryViewTypeAccess().getGroup_2(), "rule__ERepositoryViewType__Group_2__0");
			builder.put(grammarAccess.getERepositoryViewTypeAccess().getGroup_2_2(), "rule__ERepositoryViewType__Group_2_2__0");
			builder.put(grammarAccess.getERepositoryViewTypeAccess().getGroup_3(), "rule__ERepositoryViewType__Group_3__0");
			builder.put(grammarAccess.getERepositoryViewTypeAccess().getGroup_3_2(), "rule__ERepositoryViewType__Group_3_2__0");
			builder.put(grammarAccess.getEAssemblyViewTypeAccess().getGroup(), "rule__EAssemblyViewType__Group__0");
			builder.put(grammarAccess.getEAssemblyViewTypeAccess().getGroup_2(), "rule__EAssemblyViewType__Group_2__0");
			builder.put(grammarAccess.getEAssemblyViewTypeAccess().getGroup_2_2(), "rule__EAssemblyViewType__Group_2_2__0");
			builder.put(grammarAccess.getEAssemblyViewTypeAccess().getGroup_3(), "rule__EAssemblyViewType__Group_3__0");
			builder.put(grammarAccess.getEAssemblyViewTypeAccess().getGroup_3_2(), "rule__EAssemblyViewType__Group_3_2__0");
			builder.put(grammarAccess.getEAllocationViewTypeAccess().getGroup(), "rule__EAllocationViewType__Group__0");
			builder.put(grammarAccess.getEAllocationViewTypeAccess().getGroup_2(), "rule__EAllocationViewType__Group_2__0");
			builder.put(grammarAccess.getEAllocationViewTypeAccess().getGroup_2_2(), "rule__EAllocationViewType__Group_2_2__0");
			builder.put(grammarAccess.getEEnvironmentViewTypeAccess().getGroup(), "rule__EEnvironmentViewType__Group__0");
			builder.put(grammarAccess.getEEnvironmentViewTypeAccess().getGroup_2(), "rule__EEnvironmentViewType__Group_2__0");
			builder.put(grammarAccess.getEEnvironmentViewTypeAccess().getGroup_2_2(), "rule__EEnvironmentViewType__Group_2_2__0");
			builder.put(grammarAccess.getEEnvironmentViewTypeAccess().getGroup_3(), "rule__EEnvironmentViewType__Group_3__0");
			builder.put(grammarAccess.getEEnvironmentViewTypeAccess().getGroup_3_2(), "rule__EEnvironmentViewType__Group_3_2__0");
			builder.put(grammarAccess.getEComponent_ImplAccess().getGroup(), "rule__EComponent_Impl__Group__0");
			builder.put(grammarAccess.getEComponent_ImplAccess().getGroup_3(), "rule__EComponent_Impl__Group_3__0");
			builder.put(grammarAccess.getEComponent_ImplAccess().getGroup_3_2(), "rule__EComponent_Impl__Group_3_2__0");
			builder.put(grammarAccess.getEComponent_ImplAccess().getGroup_4(), "rule__EComponent_Impl__Group_4__0");
			builder.put(grammarAccess.getEComponent_ImplAccess().getGroup_4_2(), "rule__EComponent_Impl__Group_4_2__0");
			builder.put(grammarAccess.getEComponent_ImplAccess().getGroup_5(), "rule__EComponent_Impl__Group_5__0");
			builder.put(grammarAccess.getEComponent_ImplAccess().getGroup_5_2(), "rule__EComponent_Impl__Group_5_2__0");
			builder.put(grammarAccess.getEComponent_ImplAccess().getGroup_6(), "rule__EComponent_Impl__Group_6__0");
			builder.put(grammarAccess.getEComponent_ImplAccess().getGroup_6_2(), "rule__EComponent_Impl__Group_6_2__0");
			builder.put(grammarAccess.getEComponent_ImplAccess().getGroup_7(), "rule__EComponent_Impl__Group_7__0");
			builder.put(grammarAccess.getEComponent_ImplAccess().getGroup_7_2(), "rule__EComponent_Impl__Group_7_2__0");
			builder.put(grammarAccess.getEComponent_ImplAccess().getGroup_8(), "rule__EComponent_Impl__Group_8__0");
			builder.put(grammarAccess.getEInterfaceAccess().getGroup(), "rule__EInterface__Group__0");
			builder.put(grammarAccess.getEInterfaceAccess().getGroup_3(), "rule__EInterface__Group_3__0");
			builder.put(grammarAccess.getEInterfaceAccess().getGroup_3_2(), "rule__EInterface__Group_3_2__0");
			builder.put(grammarAccess.getEInterfaceAccess().getGroup_4(), "rule__EInterface__Group_4__0");
			builder.put(grammarAccess.getEInterfaceAccess().getGroup_4_2(), "rule__EInterface__Group_4_2__0");
			builder.put(grammarAccess.getEInterfaceAccess().getGroup_5(), "rule__EInterface__Group_5__0");
			builder.put(grammarAccess.getEInterfaceAccess().getGroup_5_2(), "rule__EInterface__Group_5_2__0");
			builder.put(grammarAccess.getEInterfaceAccess().getGroup_6(), "rule__EInterface__Group_6__0");
			builder.put(grammarAccess.getEInterfaceAccess().getGroup_6_2(), "rule__EInterface__Group_6_2__0");
			builder.put(grammarAccess.getEInterfaceAccess().getGroup_7(), "rule__EInterface__Group_7__0");
			builder.put(grammarAccess.getEInterfaceAccess().getGroup_7_2(), "rule__EInterface__Group_7_2__0");
			builder.put(grammarAccess.getEInterfaceAccess().getGroup_8(), "rule__EInterface__Group_8__0");
			builder.put(grammarAccess.getEInterfaceAccess().getGroup_8_2(), "rule__EInterface__Group_8_2__0");
			builder.put(grammarAccess.getEBehaviourDescriptionAccess().getGroup(), "rule__EBehaviourDescription__Group__0");
			builder.put(grammarAccess.getEBehaviourDescriptionAccess().getGroup_2(), "rule__EBehaviourDescription__Group_2__0");
			builder.put(grammarAccess.getEBehaviourDescriptionAccess().getGroup_2_2(), "rule__EBehaviourDescription__Group_2_2__0");
			builder.put(grammarAccess.getEBehaviourDescriptionAccess().getGroup_3(), "rule__EBehaviourDescription__Group_3__0");
			builder.put(grammarAccess.getEBehaviourDescriptionAccess().getGroup_3_2(), "rule__EBehaviourDescription__Group_3_2__0");
			builder.put(grammarAccess.getEBehaviourDescriptionAccess().getGroup_4(), "rule__EBehaviourDescription__Group_4__0");
			builder.put(grammarAccess.getEBehaviourDescriptionAccess().getGroup_4_2(), "rule__EBehaviourDescription__Group_4_2__0");
			builder.put(grammarAccess.getEBehaviourDescriptionAccess().getGroup_5(), "rule__EBehaviourDescription__Group_5__0");
			builder.put(grammarAccess.getEBehaviourDescriptionAccess().getGroup_5_2(), "rule__EBehaviourDescription__Group_5_2__0");
			builder.put(grammarAccess.getEExternalCallAccess().getGroup(), "rule__EExternalCall__Group__0");
			builder.put(grammarAccess.getEExternalCallAccess().getGroup_2(), "rule__EExternalCall__Group_2__0");
			builder.put(grammarAccess.getESignatureAccess().getGroup(), "rule__ESignature__Group__0");
			builder.put(grammarAccess.getESignatureAccess().getGroup_3(), "rule__ESignature__Group_3__0");
			builder.put(grammarAccess.getESignatureAccess().getGroup_4(), "rule__ESignature__Group_4__0");
			builder.put(grammarAccess.getESignatureAccess().getGroup_4_2(), "rule__ESignature__Group_4_2__0");
			builder.put(grammarAccess.getESignatureAccess().getGroup_5(), "rule__ESignature__Group_5__0");
			builder.put(grammarAccess.getESignatureAccess().getGroup_5_2(), "rule__ESignature__Group_5_2__0");
			builder.put(grammarAccess.getERepositoryAccess().getGroup(), "rule__ERepository__Group__0");
			builder.put(grammarAccess.getERepositoryAccess().getGroup_2(), "rule__ERepository__Group_2__0");
			builder.put(grammarAccess.getERepositoryAccess().getGroup_2_2(), "rule__ERepository__Group_2_2__0");
			builder.put(grammarAccess.getERepositoryAccess().getGroup_3(), "rule__ERepository__Group_3__0");
			builder.put(grammarAccess.getERepositoryAccess().getGroup_3_2(), "rule__ERepository__Group_3_2__0");
			builder.put(grammarAccess.getEParameterAccess().getNameAssignment_1(), "rule__EParameter__NameAssignment_1");
			builder.put(grammarAccess.getEParameterAccess().getTypeAssignment_3_1(), "rule__EParameter__TypeAssignment_3_1");
			builder.put(grammarAccess.getESystemAccess().getProvidesAssignment_2_1(), "rule__ESystem__ProvidesAssignment_2_1");
			builder.put(grammarAccess.getESystemAccess().getProvidesAssignment_2_2_1(), "rule__ESystem__ProvidesAssignment_2_2_1");
			builder.put(grammarAccess.getESystemAccess().getRequiresAssignment_3_1(), "rule__ESystem__RequiresAssignment_3_1");
			builder.put(grammarAccess.getESystemAccess().getRequiresAssignment_3_2_1(), "rule__ESystem__RequiresAssignment_3_2_1");
			builder.put(grammarAccess.getESystemAccess().getEncapsulatesAssignment_4_1(), "rule__ESystem__EncapsulatesAssignment_4_1");
			builder.put(grammarAccess.getESystemAccess().getEncapsulatesAssignment_4_2_1(), "rule__ESystem__EncapsulatesAssignment_4_2_1");
			builder.put(grammarAccess.getECompositeComponentAccess().getNameAssignment_1(), "rule__ECompositeComponent__NameAssignment_1");
			builder.put(grammarAccess.getECompositeComponentAccess().getProvidesInterfaceToAssignment_3_1(), "rule__ECompositeComponent__ProvidesInterfaceToAssignment_3_1");
			builder.put(grammarAccess.getECompositeComponentAccess().getProvidesInterfaceToAssignment_3_2_1(), "rule__ECompositeComponent__ProvidesInterfaceToAssignment_3_2_1");
			builder.put(grammarAccess.getECompositeComponentAccess().getUsesInterfaceFromAssignment_4_1(), "rule__ECompositeComponent__UsesInterfaceFromAssignment_4_1");
			builder.put(grammarAccess.getECompositeComponentAccess().getUsesInterfaceFromAssignment_4_2_1(), "rule__ECompositeComponent__UsesInterfaceFromAssignment_4_2_1");
			builder.put(grammarAccess.getECompositeComponentAccess().getProvidesDirectlyAssignment_5_1(), "rule__ECompositeComponent__ProvidesDirectlyAssignment_5_1");
			builder.put(grammarAccess.getECompositeComponentAccess().getProvidesDirectlyAssignment_5_2_1(), "rule__ECompositeComponent__ProvidesDirectlyAssignment_5_2_1");
			builder.put(grammarAccess.getECompositeComponentAccess().getProvidesAssignment_6_1(), "rule__ECompositeComponent__ProvidesAssignment_6_1");
			builder.put(grammarAccess.getECompositeComponentAccess().getProvidesAssignment_6_2_1(), "rule__ECompositeComponent__ProvidesAssignment_6_2_1");
			builder.put(grammarAccess.getECompositeComponentAccess().getRequiresAssignment_7_1(), "rule__ECompositeComponent__RequiresAssignment_7_1");
			builder.put(grammarAccess.getECompositeComponentAccess().getRequiresAssignment_7_2_1(), "rule__ECompositeComponent__RequiresAssignment_7_2_1");
			builder.put(grammarAccess.getECompositeComponentAccess().getEncapsulatesAssignment_8_1(), "rule__ECompositeComponent__EncapsulatesAssignment_8_1");
			builder.put(grammarAccess.getECompositeComponentAccess().getEncapsulatesAssignment_8_2_1(), "rule__ECompositeComponent__EncapsulatesAssignment_8_2_1");
			builder.put(grammarAccess.getECompositeComponentAccess().getBehaviourDescriptionAssignment_9_1(), "rule__ECompositeComponent__BehaviourDescriptionAssignment_9_1");
			builder.put(grammarAccess.getEContainerAccess().getNameAssignment_1(), "rule__EContainer__NameAssignment_1");
			builder.put(grammarAccess.getEContainerAccess().getConnectedToAssignment_3_1(), "rule__EContainer__ConnectedToAssignment_3_1");
			builder.put(grammarAccess.getEContainerAccess().getConnectedToAssignment_3_2_1(), "rule__EContainer__ConnectedToAssignment_3_2_1");
			builder.put(grammarAccess.getEAllocationContextAccess().getControlsAssignment_2_1(), "rule__EAllocationContext__ControlsAssignment_2_1");
			builder.put(grammarAccess.getEAllocationContextAccess().getControlsAssignment_2_2_1(), "rule__EAllocationContext__ControlsAssignment_2_2_1");
			builder.put(grammarAccess.getEAllocationContextAccess().getSpecifiesForAssignment_3_1(), "rule__EAllocationContext__SpecifiesForAssignment_3_1");
			builder.put(grammarAccess.getEAllocationContextAccess().getSpecifiesForAssignment_3_2_1(), "rule__EAllocationContext__SpecifiesForAssignment_3_2_1");
			builder.put(grammarAccess.getEAllocationContextAccess().getSpecifiesAssignment_4_1(), "rule__EAllocationContext__SpecifiesAssignment_4_1");
			builder.put(grammarAccess.getERequiredRoleAccess().getRoleOfAssignment_2_1(), "rule__ERequiredRole__RoleOfAssignment_2_1");
			builder.put(grammarAccess.getERequiredRoleAccess().getLinkedToAssignment_3_1(), "rule__ERequiredRole__LinkedToAssignment_3_1");
			builder.put(grammarAccess.getEProvidedRoleAccess().getRoleOfAssignment_2_1(), "rule__EProvidedRole__RoleOfAssignment_2_1");
			builder.put(grammarAccess.getEProvidedRoleAccess().getLinkedFromAssignment_3_1(), "rule__EProvidedRole__LinkedFromAssignment_3_1");
			builder.put(grammarAccess.getELinkAccess().getNameAssignment_1(), "rule__ELink__NameAssignment_1");
			builder.put(grammarAccess.getELinkAccess().getConnectsAssignment_3_1(), "rule__ELink__ConnectsAssignment_3_1");
			builder.put(grammarAccess.getELinkAccess().getConnectsAssignment_3_2_1(), "rule__ELink__ConnectsAssignment_3_2_1");
			builder.put(grammarAccess.getEAssemblyContextAccess().getNameAssignment_1(), "rule__EAssemblyContext__NameAssignment_1");
			builder.put(grammarAccess.getEAssemblyContextAccess().getAllocatedAssignment_3_1(), "rule__EAssemblyContext__AllocatedAssignment_3_1");
			builder.put(grammarAccess.getEAssemblyContextAccess().getEncapsulatedByComponentAssignment_4_1(), "rule__EAssemblyContext__EncapsulatedByComponentAssignment_4_1");
			builder.put(grammarAccess.getEAssemblyContextAccess().getEncapsulatedByComponentAssignment_4_2_1(), "rule__EAssemblyContext__EncapsulatedByComponentAssignment_4_2_1");
			builder.put(grammarAccess.getEAssemblyContextAccess().getEncapsulatedBySystemAssignment_5_1(), "rule__EAssemblyContext__EncapsulatedBySystemAssignment_5_1");
			builder.put(grammarAccess.getEAssemblyContextAccess().getEncapsulatedBySystemAssignment_5_2_1(), "rule__EAssemblyContext__EncapsulatedBySystemAssignment_5_2_1");
			builder.put(grammarAccess.getEAssemblyContextAccess().getInstantiatesAssignment_6_1(), "rule__EAssemblyContext__InstantiatesAssignment_6_1");
			builder.put(grammarAccess.getEAssemblyContextAccess().getInstantiatesAssignment_6_2_1(), "rule__EAssemblyContext__InstantiatesAssignment_6_2_1");
			builder.put(grammarAccess.getEAssemblyContextAccess().getRolesAssignment_7_1(), "rule__EAssemblyContext__RolesAssignment_7_1");
			builder.put(grammarAccess.getEAssemblyContextAccess().getRolesAssignment_7_2_1(), "rule__EAssemblyContext__RolesAssignment_7_2_1");
			builder.put(grammarAccess.getEAssemblyConnectorAccess().getLinkToAssignment_2_1(), "rule__EAssemblyConnector__LinkToAssignment_2_1");
			builder.put(grammarAccess.getEAssemblyConnectorAccess().getLinkFromAssignment_3_1(), "rule__EAssemblyConnector__LinkFromAssignment_3_1");
			builder.put(grammarAccess.getEProvidedDelegationConnectorAccess().getLinkFromAssignment_2_1(), "rule__EProvidedDelegationConnector__LinkFromAssignment_2_1");
			builder.put(grammarAccess.getEProvidedDelegationConnectorAccess().getLinkToAssignment_3_1(), "rule__EProvidedDelegationConnector__LinkToAssignment_3_1");
			builder.put(grammarAccess.getERequiredDelegationConnectorAccess().getLinkFromAssignment_2_1(), "rule__ERequiredDelegationConnector__LinkFromAssignment_2_1");
			builder.put(grammarAccess.getERequiredDelegationConnectorAccess().getLinkToAssignment_3_1(), "rule__ERequiredDelegationConnector__LinkToAssignment_3_1");
			builder.put(grammarAccess.getESystemIndependentViewPointAccess().getRepositoryViewTypeAssignment_2_1(), "rule__ESystemIndependentViewPoint__RepositoryViewTypeAssignment_2_1");
			builder.put(grammarAccess.getEAssemblyViewPointAccess().getAssemblyViewTypeAssignment_2_1(), "rule__EAssemblyViewPoint__AssemblyViewTypeAssignment_2_1");
			builder.put(grammarAccess.getEDeploymentViewPointAccess().getAllocationViewTypeAssignment_3(), "rule__EDeploymentViewPoint__AllocationViewTypeAssignment_3");
			builder.put(grammarAccess.getEDeploymentViewPointAccess().getEnvironmentViewTypeAssignment_5(), "rule__EDeploymentViewPoint__EnvironmentViewTypeAssignment_5");
			builder.put(grammarAccess.getERepositoryViewTypeAccess().getShowsInterfacesAssignment_2_1(), "rule__ERepositoryViewType__ShowsInterfacesAssignment_2_1");
			builder.put(grammarAccess.getERepositoryViewTypeAccess().getShowsInterfacesAssignment_2_2_1(), "rule__ERepositoryViewType__ShowsInterfacesAssignment_2_2_1");
			builder.put(grammarAccess.getERepositoryViewTypeAccess().getShowsComponentsAssignment_3_1(), "rule__ERepositoryViewType__ShowsComponentsAssignment_3_1");
			builder.put(grammarAccess.getERepositoryViewTypeAccess().getShowsComponentsAssignment_3_2_1(), "rule__ERepositoryViewType__ShowsComponentsAssignment_3_2_1");
			builder.put(grammarAccess.getEAssemblyViewTypeAccess().getMainArtifactsAssignment_2_1(), "rule__EAssemblyViewType__MainArtifactsAssignment_2_1");
			builder.put(grammarAccess.getEAssemblyViewTypeAccess().getMainArtifactsAssignment_2_2_1(), "rule__EAssemblyViewType__MainArtifactsAssignment_2_2_1");
			builder.put(grammarAccess.getEAssemblyViewTypeAccess().getShowsComponentsAssignment_3_1(), "rule__EAssemblyViewType__ShowsComponentsAssignment_3_1");
			builder.put(grammarAccess.getEAssemblyViewTypeAccess().getShowsComponentsAssignment_3_2_1(), "rule__EAssemblyViewType__ShowsComponentsAssignment_3_2_1");
			builder.put(grammarAccess.getEAllocationViewTypeAccess().getIncludesAssignment_2_1(), "rule__EAllocationViewType__IncludesAssignment_2_1");
			builder.put(grammarAccess.getEAllocationViewTypeAccess().getIncludesAssignment_2_2_1(), "rule__EAllocationViewType__IncludesAssignment_2_2_1");
			builder.put(grammarAccess.getEEnvironmentViewTypeAccess().getShowsLinksAssignment_2_1(), "rule__EEnvironmentViewType__ShowsLinksAssignment_2_1");
			builder.put(grammarAccess.getEEnvironmentViewTypeAccess().getShowsLinksAssignment_2_2_1(), "rule__EEnvironmentViewType__ShowsLinksAssignment_2_2_1");
			builder.put(grammarAccess.getEEnvironmentViewTypeAccess().getShowsContainersAssignment_3_1(), "rule__EEnvironmentViewType__ShowsContainersAssignment_3_1");
			builder.put(grammarAccess.getEEnvironmentViewTypeAccess().getShowsContainersAssignment_3_2_1(), "rule__EEnvironmentViewType__ShowsContainersAssignment_3_2_1");
			builder.put(grammarAccess.getEComponent_ImplAccess().getNameAssignment_1(), "rule__EComponent_Impl__NameAssignment_1");
			builder.put(grammarAccess.getEComponent_ImplAccess().getProvidesInterfaceToAssignment_3_1(), "rule__EComponent_Impl__ProvidesInterfaceToAssignment_3_1");
			builder.put(grammarAccess.getEComponent_ImplAccess().getProvidesInterfaceToAssignment_3_2_1(), "rule__EComponent_Impl__ProvidesInterfaceToAssignment_3_2_1");
			builder.put(grammarAccess.getEComponent_ImplAccess().getUsesInterfaceFromAssignment_4_1(), "rule__EComponent_Impl__UsesInterfaceFromAssignment_4_1");
			builder.put(grammarAccess.getEComponent_ImplAccess().getUsesInterfaceFromAssignment_4_2_1(), "rule__EComponent_Impl__UsesInterfaceFromAssignment_4_2_1");
			builder.put(grammarAccess.getEComponent_ImplAccess().getProvidesDirectlyAssignment_5_1(), "rule__EComponent_Impl__ProvidesDirectlyAssignment_5_1");
			builder.put(grammarAccess.getEComponent_ImplAccess().getProvidesDirectlyAssignment_5_2_1(), "rule__EComponent_Impl__ProvidesDirectlyAssignment_5_2_1");
			builder.put(grammarAccess.getEComponent_ImplAccess().getProvidesAssignment_6_1(), "rule__EComponent_Impl__ProvidesAssignment_6_1");
			builder.put(grammarAccess.getEComponent_ImplAccess().getProvidesAssignment_6_2_1(), "rule__EComponent_Impl__ProvidesAssignment_6_2_1");
			builder.put(grammarAccess.getEComponent_ImplAccess().getRequiresAssignment_7_1(), "rule__EComponent_Impl__RequiresAssignment_7_1");
			builder.put(grammarAccess.getEComponent_ImplAccess().getRequiresAssignment_7_2_1(), "rule__EComponent_Impl__RequiresAssignment_7_2_1");
			builder.put(grammarAccess.getEComponent_ImplAccess().getBehaviourDescriptionAssignment_8_1(), "rule__EComponent_Impl__BehaviourDescriptionAssignment_8_1");
			builder.put(grammarAccess.getEInterfaceAccess().getNameAssignment_1(), "rule__EInterface__NameAssignment_1");
			builder.put(grammarAccess.getEInterfaceAccess().getResultsInAssignment_3_1(), "rule__EInterface__ResultsInAssignment_3_1");
			builder.put(grammarAccess.getEInterfaceAccess().getResultsInAssignment_3_2_1(), "rule__EInterface__ResultsInAssignment_3_2_1");
			builder.put(grammarAccess.getEInterfaceAccess().getProvidedByComponentAssignment_4_1(), "rule__EInterface__ProvidedByComponentAssignment_4_1");
			builder.put(grammarAccess.getEInterfaceAccess().getProvidedByComponentAssignment_4_2_1(), "rule__EInterface__ProvidedByComponentAssignment_4_2_1");
			builder.put(grammarAccess.getEInterfaceAccess().getProvidedBySystemAssignment_5_1(), "rule__EInterface__ProvidedBySystemAssignment_5_1");
			builder.put(grammarAccess.getEInterfaceAccess().getProvidedBySystemAssignment_5_2_1(), "rule__EInterface__ProvidedBySystemAssignment_5_2_1");
			builder.put(grammarAccess.getEInterfaceAccess().getRequiredByComponentAssignment_6_1(), "rule__EInterface__RequiredByComponentAssignment_6_1");
			builder.put(grammarAccess.getEInterfaceAccess().getRequiredByComponentAssignment_6_2_1(), "rule__EInterface__RequiredByComponentAssignment_6_2_1");
			builder.put(grammarAccess.getEInterfaceAccess().getRequiredBySystemAssignment_7_1(), "rule__EInterface__RequiredBySystemAssignment_7_1");
			builder.put(grammarAccess.getEInterfaceAccess().getRequiredBySystemAssignment_7_2_1(), "rule__EInterface__RequiredBySystemAssignment_7_2_1");
			builder.put(grammarAccess.getEInterfaceAccess().getSignatureAssignment_8_1(), "rule__EInterface__SignatureAssignment_8_1");
			builder.put(grammarAccess.getEInterfaceAccess().getSignatureAssignment_8_2_1(), "rule__EInterface__SignatureAssignment_8_2_1");
			builder.put(grammarAccess.getEBehaviourDescriptionAccess().getInternalActionAssignment_2_1(), "rule__EBehaviourDescription__InternalActionAssignment_2_1");
			builder.put(grammarAccess.getEBehaviourDescriptionAccess().getInternalActionAssignment_2_2_1(), "rule__EBehaviourDescription__InternalActionAssignment_2_2_1");
			builder.put(grammarAccess.getEBehaviourDescriptionAccess().getLoopAssignment_3_1(), "rule__EBehaviourDescription__LoopAssignment_3_1");
			builder.put(grammarAccess.getEBehaviourDescriptionAccess().getLoopAssignment_3_2_1(), "rule__EBehaviourDescription__LoopAssignment_3_2_1");
			builder.put(grammarAccess.getEBehaviourDescriptionAccess().getBranchAssignment_4_1(), "rule__EBehaviourDescription__BranchAssignment_4_1");
			builder.put(grammarAccess.getEBehaviourDescriptionAccess().getBranchAssignment_4_2_1(), "rule__EBehaviourDescription__BranchAssignment_4_2_1");
			builder.put(grammarAccess.getEBehaviourDescriptionAccess().getExternalCallAssignment_5_1(), "rule__EBehaviourDescription__ExternalCallAssignment_5_1");
			builder.put(grammarAccess.getEBehaviourDescriptionAccess().getExternalCallAssignment_5_2_1(), "rule__EBehaviourDescription__ExternalCallAssignment_5_2_1");
			builder.put(grammarAccess.getEExternalCallAccess().getToAssignment_2_1(), "rule__EExternalCall__ToAssignment_2_1");
			builder.put(grammarAccess.getESignatureAccess().getNameAssignment_1(), "rule__ESignature__NameAssignment_1");
			builder.put(grammarAccess.getESignatureAccess().getReturnTypeAssignment_3_1(), "rule__ESignature__ReturnTypeAssignment_3_1");
			builder.put(grammarAccess.getESignatureAccess().getCorrespondsToAssignment_4_1(), "rule__ESignature__CorrespondsToAssignment_4_1");
			builder.put(grammarAccess.getESignatureAccess().getCorrespondsToAssignment_4_2_1(), "rule__ESignature__CorrespondsToAssignment_4_2_1");
			builder.put(grammarAccess.getESignatureAccess().getParameterAssignment_5_1(), "rule__ESignature__ParameterAssignment_5_1");
			builder.put(grammarAccess.getESignatureAccess().getParameterAssignment_5_2_1(), "rule__ESignature__ParameterAssignment_5_2_1");
			builder.put(grammarAccess.getERepositoryAccess().getComponentAssignment_2_1(), "rule__ERepository__ComponentAssignment_2_1");
			builder.put(grammarAccess.getERepositoryAccess().getComponentAssignment_2_2_1(), "rule__ERepository__ComponentAssignment_2_2_1");
			builder.put(grammarAccess.getERepositoryAccess().getInterfaceAssignment_3_1(), "rule__ERepository__InterfaceAssignment_3_1");
			builder.put(grammarAccess.getERepositoryAccess().getInterfaceAssignment_3_2_1(), "rule__ERepository__InterfaceAssignment_3_2_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private MyDslGrammarAccess grammarAccess;

	@Override
	protected InternalMyDslParser createParser() {
		InternalMyDslParser result = new InternalMyDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public MyDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MyDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
