<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="component_based" nsURI="http://www.example.org/component_based"
    nsPrefix="component_based">
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="EViewPoint" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="EViewType" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ESystemIndependentViewPoint" eSuperTypes="#//EViewPoint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="repositoryviewtype" lowerBound="1"
        eType="#//ERepositoryViewType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ERepositoryViewType" eSuperTypes="#//EViewType">
    <eOperations name="showComponents"/>
    <eOperations name="showInterfaces"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EAssemblyViewType" eSuperTypes="#//EViewType">
    <eOperations name="showConcreteComponents"/>
    <eOperations name="showComponentConnections"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EAssemblyViewPoint" eSuperTypes="#//EViewPoint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="assemblyviewtype" lowerBound="1"
        eType="#//EAssemblyViewType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EDeploymentViewPoint" eSuperTypes="#//EViewPoint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="environmentviewtype" lowerBound="1"
        eType="#//EEnvironmentViewType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allocationviewtype" lowerBound="1"
        eType="#//EAllocationViewType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EEnvironmentViewType" eSuperTypes="#//EViewType">
    <eOperations name="showContainers"/>
    <eOperations name="showContainerConnections"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contains" upperBound="-1"
        eType="#//EAllocationContext" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="shows" upperBound="-1"
        eType="#//EContainer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EAllocationViewType" eSuperTypes="#//EViewType">
    <eOperations name="showComponentAllocations"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EVoid" instanceClassName="java.lang.Void"/>
  <eClassifiers xsi:type="ecore:EClass" name="ERepository">
    <eStructuralFeatures xsi:type="ecore:EReference" name="component" upperBound="-1"
        eType="#//EComponent" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="interface" upperBound="-1"
        eType="#//EInterface" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ESignature">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="returnType" lowerBound="1"
        eType="#//PossibleReturnTypes" defaultValueLiteral="Void"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" upperBound="-1"
        eType="#//EParameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="correspondsTo" upperBound="-1"
        eType="#//EService"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EComponent">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="providesConstraint"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="providesConstraint" value=" self.provides -> size() > 0 implies self.provides.signature.correspondsTo -> size() > 0"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requires" upperBound="-1"
        eType="#//EInterface"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="providesInterfaceTo" upperBound="-1"
        eType="#//EComponent" eOpposite="#//EComponent/usesInterfaceFrom"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="behaviourDescription" eType="#//EBehaviourDescription"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="usesInterfaceFrom" upperBound="-1"
        eType="#//EComponent" eOpposite="#//EComponent/providesInterfaceTo"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="provides" upperBound="-1"
        eType="#//EInterface"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="getsInstantiatedBy" upperBound="-1"
        eType="#//EAssemblyContext" eOpposite="#//EAssemblyContext/instantiates"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EInterface">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="signature" upperBound="-1"
        eType="#//ESignature" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resultsIn" upperBound="-1"
        eType="#//ERole"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dfe" eType="#//ESignature"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EParameter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//PossibleReturnTypes"
        defaultValueLiteral="Boolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PossibleReturnTypes">
    <eLiterals name="BOOLEAN" literal="Boolean"/>
    <eLiterals name="CHAR" value="1" literal="Char"/>
    <eLiterals name="DATE" value="2" literal="Date"/>
    <eLiterals name="DOUBLE" value="3" literal="Double"/>
    <eLiterals name="FLOAT" value="4" literal="Float"/>
    <eLiterals name="LIST" value="5" literal="List"/>
    <eLiterals name="INT" value="6" literal="Int"/>
    <eLiterals name="LONG" value="7" literal="Long"/>
    <eLiterals name="MAP" value="8" literal="Map"/>
    <eLiterals name="STRING" value="9" literal="String"/>
    <eLiterals name="VOID" value="10" literal="Void"/>
    <eLiterals name="EOBJECT" value="11"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EService"/>
  <eClassifiers xsi:type="ecore:EClass" name="EBehaviourDescription">
    <eStructuralFeatures xsi:type="ecore:EReference" name="internalAction" upperBound="-1"
        eType="#//EInternalAction" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="loop" upperBound="-1" eType="#//ELoop"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="branch" upperBound="-1"
        eType="#//EBranch" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="externalcall" upperBound="-1"
        eType="#//EExternalCall" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EInternalAction"/>
  <eClassifiers xsi:type="ecore:EClass" name="ELoop"/>
  <eClassifiers xsi:type="ecore:EClass" name="EBranch"/>
  <eClassifiers xsi:type="ecore:EClass" name="EExternalCall">
    <eStructuralFeatures xsi:type="ecore:EReference" name="to" lowerBound="1" eType="#//EService"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EAssemblyContext">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="instantiates" lowerBound="1"
        eType="#//EComponent" eOpposite="#//EComponent/getsInstantiatedBy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="roles" upperBound="-1"
        eType="#//ERole" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allocated" upperBound="-1"
        eType="#//EContainer" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ECompositeComponent" eSuperTypes="#//EComponent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="encapsulates" upperBound="-1"
        eType="#//EAssemblyContext"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ESystem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="encapsulates" upperBound="-1"
        eType="#//EAssemblyContext"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="provides" lowerBound="1"
        upperBound="-1" eType="#//EInterface"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EProvidedRole" eSuperTypes="#//ERole"/>
  <eClassifiers xsi:type="ecore:EClass" name="ERequiredRole" eSuperTypes="#//ERole"/>
  <eClassifiers xsi:type="ecore:EClass" name="ERole" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="EDelegationConnector" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="EProvidedDelegationConnector" eSuperTypes="#//EDelegationConnector">
    <eStructuralFeatures xsi:type="ecore:EReference" name="linkFrom" lowerBound="1"
        eType="#//EInterface"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="linkTo" lowerBound="1"
        eType="#//EProvidedRole"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ERequiredDelegationConnector" eSuperTypes="#//EDelegationConnector">
    <eStructuralFeatures xsi:type="ecore:EReference" name="linkFrom" lowerBound="1"
        eType="#//ERequiredRole"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="linkTo" lowerBound="1"
        eType="#//EInterface"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EAssemblyConnector">
    <eStructuralFeatures xsi:type="ecore:EReference" name="linkFrom" lowerBound="1"
        eType="#//EProvidedRole"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="linkTo" lowerBound="1"
        eType="#//ERequiredRole"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allocatedContainers" upperBound="-1"
        eType="#//EContainer" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allocatedLinks" upperBound="-1"
        eType="#//ELink" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EContainer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ELink">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connects" lowerBound="2"
        upperBound="-1" eType="#//EContainer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="shows" upperBound="-1"
        eType="#//EEnvironmentViewType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EAllocationContext">
    <eStructuralFeatures xsi:type="ecore:EReference" name="controls" upperBound="-1"
        eType="#//EContainer"/>
  </eClassifiers>
</ecore:EPackage>
